### ISSUE TITLE
Sorting issues on dynamic layout 

### ISSUE THREAD

**Issue by timfish** [oribella/aurelia-sortable#14]
I've got a responsive layout using [material design lite](https://www.getmdl.io/). When I resize the window I can get into a state where I can't drag items in to the far ends of the draggable area. 

I've set `scroll.bind: '.mdl-layout__content'` but I've noticed that when the left drawer menu is displayed it adds a large margin to `.mdl-layout__content` to leave space for the drawer. When the viewport is made smaller this margin is removed.

My guess (so far) is when the margin is added/remove `aurelia-sortable` is not re-calculating the absolute positions of the sortable items. Is there any way I can re-trigger this when the layout changes?

**Comment by timfish** [comment]
I sent you a PM on Gitter with a video showing the issue I'm having.

**Comment by stoffeastrom** [comment]
So, this is a problem how the layout is built. The mdl is defining `margin-left` for the drawer which makes the `getBoundingClientRect` to not report "correct". Also the use of `flexbox` needs to be rewritten so it actually gets the layout that it looks like it has. What I mean is that it looks "right" but when you look into the layout and do `getBoundingClientRect`it will report differently than you think. The problem with `flexbox` is that even if it solves responsive layouts it needs to be used correctly for this kind of scenarios.

I'm not sure this kind of scenario could be supported ootb since I don't want to have any special handling and I'm not sure we could detect this in a good way. So the best way is to make sure that your layout is "correct" meaning that if you do `getBoundingClientRect` on a `oa-sortable-item` it should report correct regarding to the `offsetParent`.

One "solution" I'm thinking of would be to introduce something like a `dragOffset` which could be bound and used when calculating the start position.

**Comment by timfish** [comment]
Thank you for looking into this for me. 

I've been looking into other drag-drop implementations which don't appear to exhibit this behaviour with this layout, namely [dragula](https://github.com/bevacqua/dragula/). It [also uses](https://github.com/bevacqua/dragula/blob/697f228a02d79331a55518b5925c165200a26726/dragula.js#L419) `getBoundingClientRect`. It looks like it [still uses](https://github.com/bevacqua/dragula/blob/697f228a02d79331a55518b5925c165200a26726/dragula.js#L525) it for calculating the offset.

**Comment by stoffeastrom** [comment]
So you are saying that they use getboundingclientrect but it works?

**Comment by stoffeastrom** [comment]
I just briefly look into the code you linked. They are using a completely different strategy for the dragging element. It's being cloned and added `o.mirrorContainer` which seems to be `body` by default. While the strategy in `aurelia-sortable` is to absolute position the dragging element and add a placeholder. It's a simple approach utilising Aurelia binding functionality. So that's the reason the `getBoundingClientRect` needs to report the correct position relative to it's `offsetParent` else it will not work as expected. Do they support that you can do manual scroll / auto scrolling?

There might be other strategies for the `drag` element and if we can come up with a better solution I'm all ears and PR's welcome

**Comment by stoffeastrom** [comment]
So if this should be supported the `drag` needs to be cloned and added to the `viewport` e.g `document.body`. The `dragBoundingRect` should always be the `getBoundingClientRect` of the `oa-sortable`
I will look into it some more...

**Comment by timfish** [comment]
dragula doesn't currently support [auto scrolling](https://github.com/bevacqua/dragula/issues/327) but mouse and keyboard scroll still work. There can apparently be issues with aurelia as it modifies the DOM. The recommended approach with aurelia+dragula is to cancel the drop and modify the underlying bound list manually and let aurelia adjust the DOM.

**Comment by stoffeastrom** [comment]
@timfish I've looked into this a bit more. Thanks for the demo project which helped a lot. I think this could be doable. I've changed so the drag clones the item and adds it to the `document.body`. I have to fix the scrolling part thought which will not work ootb. Also the `dragBoundingRect` needs to be updated.

So the `placeholder` logic will be removed and the `drag` adds it's clone to the `document.body`. Instead of moving around the `placeholder`we now move around the "real" item. On `end` we only have to report `fromIx` and the current position of the item. On `cancel` we should remove the `drag` clone and move back the item to it's original position.

**Comment by stoffeastrom** [comment]
@timfish try out the latest on master. It should support your use case now. Actually the best experience right now is to have `document` scroll which also correctly handles `drag` boundaries. For scenarios where the scroll is not on the `viewport` but as a parent or direct on the `oa-sortable` the `drag` boundaries are not perfect yet since we are now adding the `drag` into the `viewport` we need to handle `viewport` coordinates vs `page` coordinates

**Comment by stoffeastrom** [comment]
@timfish any updates regarding this?

**Comment by timfish** [comment]
@stoffeastrom sorry I missed this. I'll give it a try tomorrow...

**Comment by timfish** [comment]
Thanks for attempting to fix this. I did have to manually install `aurelia-event-aggregator` as I was getting an error that it couldn't be found. After that, I'm getting an exception in `drag.pin` because `this.item` is null. Not had a chance to look any further than that, but will take another look tomorrow.

![image](https://cloud.githubusercontent.com/assets/1150298/14054423/072312a4-f2d1-11e5-97dd-1e4bc3ed2686.png)

**Comment by stoffeastrom** [comment]
Hm weird. That should be the `item` bound in `oa-sortable-item`

**Comment by stoffeastrom** [comment]
@timfish I added a material design lite [demo](http://oribella.github.io/aurelia-sortable/#/mdl) for you!

**Comment by timfish** [comment]
That appears to be working very well. At least I now know its something I'm doing wrong my end! Shall I close this bug or do you want to do it when you push the changes in a release?

**Comment by stoffeastrom** [comment]
I can close it in a new release!
