### ISSUE TITLE
Copy DOM element with styling

### ISSUE THREAD

**Issue by PWKad** [oribella/aurelia-sortable#22]
After testing the two versions of `aurelia-sortable` one thing that is very nice about the other is that the DOM element itself is copied and all of the styles look the same in mid-flight, it would be nice if the two of you could collaborate some how to get that functionality in this lib as well.

**Comment by stoffeastrom** [comment]
@PWKad I'm not sure I understand what you  mean :)? Which two versions?

**Comment by stoffeastrom** [comment]
Aha you mean there is another `aurelia-sortable`

**Comment by stoffeastrom** [comment]
I'm cloning the drag element and putting it into the body

```
  pin() {
    this.item.sortingClass = this.sortingClass;
    this.clone = this.element.cloneNode(true);
    this.clone.style.position = "absolute";
    this.clone.style.width = this.rect.width + "px";
    this.clone.style.height = this.rect.height + "px";
    this.clone.style.pointerEvents = "none";
    this.clone.style.margin = 0;
    this.clone.style.zIndex = this.dragZIndex;
    document.body.appendChild(this.clone);
  }
```
So what you are saying is that the styles are changing?
Is it easy to repro?

**Comment by PWKad** [comment]
You are cloning it at the bottom of the body I believe the other version kind of does it in place so the nested styles still apply I didn't dig in to it too much though was just comparing

**Comment by stoffeastrom** [comment]
Ok, Yeah one of the earlier versions the cloned element was added in place however then it wasn't possible to support document scrolling which is used in for example material design lite layouts.

**Comment by stoffeastrom** [comment]
I guess it's possible to add some kind of `cloneStrategy` to support both but it's not something I've looked into.

**Comment by stoffeastrom** [comment]
I'll close this for now. Please re-open if wanted

**Comment by gavinaiken** [comment]
Ah, yes this is also affecting me now. The old version had the cloned element in place in the DOM so css class selectors worked the same, with the new functionality of it being cloned at the bottom I see different styles. I can work around it, but the old functionality worked better for my use case. :(

**Comment by stoffeastrom** [comment]
:(

It might be possible to set which container that should be used. Problem is to make sure it's moved correctly with scrolling and all. Could you make a [gist](https://gist.run/?id=351569c3bad333bb555682f9a9810bcc) to show case the problem.

**Comment by gavinaiken** [comment]
Yes will get a gist set up tomorrow to illustrate this.

**Comment by gavinaiken** [comment]
Here is an example of the problem I had to work around in the latest version. https://gist.run/?id=6f5ba6f20af646efbdf51c65a6d35568

You should see that the list items are pale blue, but that while they are being dragged, they turn red. This is because the pale blue is set as a result of them being inside the `body-wrapper` class, but when the clone is added to the bottom of the body it is outside that context so it gets the default red color instead.

I have worked around it (so it's not a big issue for me) by adding new css classes to the items being dragged to set their css properties without reliance on their nested context (probably best practice anyway!) but FWIW thought I would share this example anyway.

**Comment by stoffeastrom** [comment]
Ok, it was as I expected and I'm glad you worked around it since I think one of the good things when refactoring the plugin was to make it more simple. Adding it "inline" complicates things tremendously since  you have to consider all scrollbars that could effect how the element is placed. "Simple" case would be that the `oa-sortable` is the only one having scrollbar but I still think it's much easier to only consider the `pageScroll` and nothing else.

Lets close this for now and re-open if it's something that's really needed.
